### PR TITLE
Introduces exception handling for when encountering unprintable characters during training.

### PR DESCRIPTION
**Pull request by LukeB42**
Introduces two new flags in `train.py`: `--model` (choice of GRU and LSTM)
and `--bidirectional`, which works with either unit type.

### CODE REVIEW

**Comment by spro** [comment]
Looking good. I'm not sure about the bidirectional option though - how does that work during evaluation/generation? We don't have a future context to go backwards from.

**Comment by LukeB42** [comment]
Well spotted. To make use of bidirectional units the sampler would have to be tasked with imputation and fed some future state to condition from. Incongruent at the moment though.

**Comment by spro** [comment]
I'll merge this if you just remove the bidirectional option (unless you can find an immediate use for it).

**Comment by LukeB42** [comment]
Done.

**Comment by spro** [comment]
Awesome thanks.

**Pull request merged**
